const js = require( '@eslint/js' );
const jsdoc = require( 'eslint-plugin-jsdoc' );

module.exports = [
  js.configs.recommended,
  jsdoc.configs[ 'flat/recommended' ],
  {
    'plugins': {
      jsdoc
    },
    'languageOptions': {
      'ecmaVersion': 2024,
      'sourceType': 'commonjs',
      'globals': {
        'console': 'readonly',
        'fetch': 'readonly',
        'process': 'readonly',
        '__dirname': 'readonly',
        '__filename': 'readonly',
        'Buffer': 'readonly',
        'global': 'readonly',
        'describe': 'readonly',
        'test': 'readonly',
        'expect': 'readonly',
        'jest': 'readonly',
        'beforeEach': 'readonly'
      }
    },
    'rules': {
      'no-useless-backreference': 'error',
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'class-methods-use-this': 'error',
      'complexity': [ 'error', 18 ],
      'consistent-return': 'error',
      'curly': 'error',
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-location': 'error',
      'dot-notation': 'error',
      'eqeqeq': 'error',
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'no-else-return': 'error',
      'no-empty-function': 'error',
      'no-empty-pattern': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-implicit-coercion': [ 'error', { 'allow': [ '~' ] } ],
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'error',
      'no-proto': 'error',
      'no-restricted-properties': 'error',
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-self-compare': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      'no-warning-comments': 'warn',
      'prefer-named-capture-group': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'radix': 'error',
      'require-await': 'error',
      'require-unicode-regexp': 'error',
      'vars-on-top': 'error',
      'wrap-iife': 'error',
      'yoda': 'error',
      'no-shadow': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'error',
      'no-use-before-define': 'error',
      'array-bracket-newline': 'error',
      'array-bracket-spacing': [ 'error', 'always' ],
      'array-element-newline': [ 'error', 'consistent' ],
      'block-spacing': 'error',
      'brace-style': 'error',
      'camelcase': 'error',
      'capitalized-comments': 'error',
      'comma-dangle': 'error',
      'comma-spacing': 'error',
      'comma-style': 'error',
      'computed-property-spacing': [ 'error', 'always' ],
      'consistent-this': 'error',
      'func-call-spacing': 'error',
      'func-name-matching': 'error',
      'func-names': 'error',
      'func-style': 'error',
      'function-paren-newline': 'error',
      'indent': [ 'error', 2, { 'SwitchCase': 1 } ],
      'key-spacing': 'error',
      'keyword-spacing': 'error',
      'line-comment-position': 'error',
      'linebreak-style': [ 'error', 'unix' ],
      'lines-between-class-members': 'error',
      'max-depth': [ 'error', 5 ],
      'max-len': [ 'error', 160 ],
      'max-lines': [ 'error', 500 ],
      'max-lines-per-function': [ 'error', 50 ],
      'max-nested-callbacks': 'error',
      'max-params': [ 'error', 5 ],
      'max-statements': [ 'error', 25 ],
      'max-statements-per-line': 'error',
      'multiline-comment-style': 'error',
      'multiline-ternary': [ 'error', 'never' ],
      'new-cap': 'error',
      'new-parens': 'error',
      'no-array-constructor': 'error',
      'no-bitwise': [ 'error', { 'allow': [ '~' ] } ],
      'no-continue': 'error',
      'no-inline-comments': 'error',
      'no-lonely-if': 'error',
      'no-mixed-operators': 'error',
      'no-multi-assign': 'error',
      'no-multiple-empty-lines': 'error',
      'no-negated-condition': 'error',
      'no-nested-ternary': 'error',
      'no-new-object': 'error',
      'no-trailing-spaces': 'error',
      'no-underscore-dangle': 'error',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': 'error',
      'object-curly-newline': 'error',
      'object-curly-spacing': [ 'error', 'always' ],
      'object-property-newline': 'error',
      'one-var-declaration-per-line': 'error',
      'operator-assignment': 'error',
      'operator-linebreak': 'error',
      'padded-blocks': [ 'error', 'never' ],
      'padding-line-between-statements': 'error',
      'quote-props': 'error',
      'quotes': [ 'error', 'single' ],
      'semi': [ 'error', 'always' ],
      'semi-spacing': 'error',
      'semi-style': 'error',
      'space-before-blocks': 'error',
      'space-before-function-paren': 'error',
      'space-in-parens': [ 'error', 'always' ],
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'spaced-comment': 'error',
      'switch-colon-spacing': 'error',
      'template-tag-spacing': 'error',
      'arrow-body-style': 'error',
      'arrow-parens': 'error',
      'arrow-spacing': 'error',
      'no-confusing-arrow': 'error',
      'no-duplicate-imports': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-destructuring': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'rest-spread-spacing': 'error',
      'sort-imports': 'error',
      'symbol-description': 'error',
      'template-curly-spacing': 'error',
      'yield-star-spacing': 'error',
      'jsdoc/require-jsdoc': [
        'error',
        {
          'require': {
            'FunctionDeclaration': true,
            'MethodDefinition': true,
            'ClassDeclaration': true,
            'ArrowFunctionExpression': true,
            'FunctionExpression': true
          }
        }
      ],
      'jsdoc/require-description': 'error',
      'jsdoc/require-param-description': 'error',
      'jsdoc/require-returns-description': 'error',
      'jsdoc/check-param-names': 'error',
      'jsdoc/check-tag-names': 'error',
      'jsdoc/check-types': 'error',
      'jsdoc/no-undefined-types': 'error'
    }
  }
];